# Generated by Django 4.1.1 on 2022-09-12 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_calendar_day_remove_calendar_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
